/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'tertiary-fixed': '#ffdea5',
        'outline-variant': '#c3c8c1',
        'on-primary-fixed-variant': '#364c3c',
        'on-error-container': '#93000a',
        'secondary-fixed-dim': '#bfc5e4',
        surface: '#faf9f5',
        'secondary-fixed': '#dce1ff',
        'secondary-container': '#d8defe',
        'surface-tint': '#4d6453',
        'on-surface': '#1b1c1a',
        'primary-fixed': '#d0e9d4',
        'on-tertiary': '#ffffff',
        error: '#ba1a1a',
        'inverse-surface': '#2f312e',
        'tertiary-fixed-dim': '#e9c176',
        'surface-container-highest': '#e3e2df',
        'on-secondary-fixed': '#141a32',
        'on-primary-container': '#819986',
        primary: '#061b0e',
        'surface-dim': '#dbdad6',
        'surface-container': '#efeeea',
        'surface-container-lowest': '#ffffff',
        'tertiary-container': '#3a2800',
        'inverse-on-surface': '#f2f1ed',
        'surface-container-low': '#f4f4f0',
        'on-primary': '#ffffff',
        'inverse-primary': '#b4cdb8',
        'on-secondary-fixed-variant': '#3f465f',
        'on-secondary': '#ffffff',
        'on-tertiary-fixed-variant': '#5d4201',
        outline: '#737973',
        'on-primary-fixed': '#0b2013',
        'error-container': '#ffdad6',
        tertiary: '#211500',
        secondary: '#575d78',
        'on-tertiary-fixed': '#261900',
        'surface-variant': '#e3e2df',
        background: '#faf9f5',
        'on-background': '#1b1c1a',
        'primary-container': '#1b3022',
        'on-error': '#ffffff',
        'surface-bright': '#faf9f5',
        'on-tertiary-container': '#b18d48',
        'on-secondary-container': '#5b617d',
        'on-surface-variant': '#434843',
        'surface-container-high': '#e9e8e4',
        'primary-fixed-dim': '#b4cdb8',
        gold: '#C5A059',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'section-padding': '120px',
        unit: '8px',
        gutter: '32px',
        'container-max': '1280px',
        'margin-desktop': '64px',
        'margin-mobile': '20px',
      },
      fontFamily: {
        'body-md': ['Montserrat', 'sans-serif'],
        'headline-lg': ['Playfair Display', 'serif'],
        'label-lg': ['Montserrat', 'sans-serif'],
        'display-lg': ['Playfair Display', 'serif'],
        'headline-lg-mobile': ['Playfair Display', 'serif'],
        'label-sm': ['Montserrat', 'sans-serif'],
        'headline-md': ['Playfair Display', 'serif'],
        'body-lg': ['Montserrat', 'sans-serif'],
      },
      fontSize: {
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-lg': ['48px', { lineHeight: '56px', fontWeight: '600' }],
        'label-lg': ['14px', { lineHeight: '20px', letterSpacing: '0.1em', fontWeight: '600' }],
        'display-lg': ['64px', { lineHeight: '72px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg-mobile': ['32px', { lineHeight: '40px', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '500' }],
        'headline-md': ['32px', { lineHeight: '40px', fontWeight: '500' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
};
